### ISSUE TITLE
Regarding the shapefiles for metropolitan cities

### ISSUE THREAD

**Issue by achakraborty8** [datta07/INDIAN-SHAPEFILES#11]
Hello! First and foremost, it is an amazing amount of work by compiling the shapefiles of so many spatial features across India. I wanted to know what definition of metropolitan cities you have chosen while compiling the shapefiles ? Is it to do with cities with population in excess of 10 lakh? Also, is it possible to expand the metropolitan cities project to all the metropolitan cities like Kolkata and others? I again, thank you a lot in compiling such an amazing spatial dataset.

**Comment by achakraborty8** [comment]
Also, I intended to use these spatial datasets as a part of a report to the stakeholders. How can I cite this work?

**Comment by datta07** [comment]
Hello!

Thank you so much for your kind words and appreciation—I’m really glad you find the dataset valuable.

Regarding the metropolitan cities, I’ve been adding them based on population rankings. I had to skip a few cities, like Kolkata, due to issues with shape or attribute data, but I’m working on fixing this and plan to add the missing cities soon. I also intend to expand the dataset to include the top 50 cities by population in the near future, so stay tuned!

For citing this work in your report to stakeholders, you can use the following format:

**Author:** Akula Guru Datta  
**Title:** INDIAN-SHAPEFILES  
**Repository:** GitHub  
**URL:** [https://github.com/datta07/INDIAN-SHAPEFILES](https://github.com/datta07/INDIAN-SHAPEFILES)  
**Date Accessed:** [Add the date you accessed the dataset here]

If you need any adjustments or have specific citation requirements, feel free to let me know. Thanks again for your feedback—it’s motivating and helps me keep improving the project!
